-- Create the blogs table
CREATE TABLE blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT NOT NULL,
  author TEXT DEFAULT 'Anonymous',
  authorRole TEXT,
  imagePath TEXT,
  date TEXT,
  ownerId TEXT,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to read blogs
CREATE POLICY "Allow public read access" ON blogs FOR SELECT USING (true);

-- Create a policy that allows anyone to insert
CREATE POLICY "Allow public insert access" ON blogs FOR INSERT WITH CHECK (true);

-- Create a policy that allows updates
CREATE POLICY "Allow updates" ON blogs FOR UPDATE USING (true);

-- Create a policy that allows deletes
CREATE POLICY "Allow deletes" ON blogs FOR DELETE USING (true);
